# example configuration

# configure release bind
release_bind = [ "KeyA", "KeyS", "KeyD", "KeyF" ]

# optional port (defaults to 4242)
port = 4242

# list of authorized tls certificate fingerprints that
# are accepted for incoming traffic
[authorized_fingerprints]
"ab:d2:31:cf:aa:b3:8c:cb:5f:7c:84:95:42:07:1c:78:23:06:61:f8:20:8f:e0:e7:d6:4b:9e:cb:f2:1d:11:84" = "laptop"
"d9:2a:61:60:b4:ab:1e:c5:e4:d7:89:23:a8:c3:cb:1f:dd:fd:6f:36:f7:5a:80:33:ff:aa:7f:4d:31:13:28:a2" = "desktop"

# define a client on the right side with host name "iridium"
[[clients]]
# position (left | right | top | bottom)
position = "right"
# hostname
hostname = "laptop"
# activate this client immediately when lan-mouse is started
activate_on_startup = true
# optional list of (known) ip addresses
ips = ["192.168.0.123"]
port = 4242

# define a client on the left side with IP address 192.168.178.189
[[clients]]
position = "left"
# The hostname is optional: When no hostname is specified,
# at least one ip address needs to be specified.
hostname = "desktop"
# ips for ethernet and wifi
ips = ["192.168.0.103"]
# optional port
port = 4242
